# Site settings
title: CCNx Protocol
email: ccnx-spec@ccnx.org
description: CCNx Protocol Specifications
baseurl: /ccnx-spec/
url: "ccnx.org"
twitter_username: ccnx
github_username:  parc

# Build settings
markdown: kramdown
