TARGETS_DRAFTS := draft-irtf-icnrg-ccnxmessages draft-irtf-icnrg-ccnxsemantics draft-mosko-icnrg-beginendfragment draft-mosko-icnrg-cachecontrol draft-mosko-icnrg-ccnxchunking draft-mosko-icnrg-ccnxserialversion draft-mosko-icnrg-ccnxtimeversion draft-mosko-icnrg-ccnxurischeme draft-mosko-icnrg-selectors draft-rfc8569 draft-tschudin-icnrg-flic
TARGETS_TAGS := 
draft-irtf-icnrg-ccnxmessages-00.xml: draft-irtf-icnrg-ccnxmessages.xml
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
draft-irtf-icnrg-ccnxsemantics-00.xml: draft-irtf-icnrg-ccnxsemantics.xml
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
draft-mosko-icnrg-beginendfragment-00.xml: draft-mosko-icnrg-beginendfragment.xml
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
draft-mosko-icnrg-cachecontrol-00.xml: draft-mosko-icnrg-cachecontrol.xml
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
draft-mosko-icnrg-ccnxchunking-00.xml: draft-mosko-icnrg-ccnxchunking.xml
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
draft-mosko-icnrg-ccnxserialversion-00.xml: draft-mosko-icnrg-ccnxserialversion.xml
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
draft-mosko-icnrg-ccnxtimeversion-00.xml: draft-mosko-icnrg-ccnxtimeversion.xml
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
draft-mosko-icnrg-ccnxurischeme-00.xml: draft-mosko-icnrg-ccnxurischeme.xml
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
draft-mosko-icnrg-selectors-00.xml: draft-mosko-icnrg-selectors.xml
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
draft-tschudin-icnrg-flic-00.md: draft-tschudin-icnrg-flic.md
	sed -e s/draft-irtf-icnrg-ccnxmessages-latest/draft-irtf-icnrg-ccnxmessages-00/g -e s/draft-irtf-icnrg-ccnxsemantics-latest/draft-irtf-icnrg-ccnxsemantics-00/g -e s/draft-mosko-icnrg-beginendfragment-latest/draft-mosko-icnrg-beginendfragment-00/g -e s/draft-mosko-icnrg-cachecontrol-latest/draft-mosko-icnrg-cachecontrol-00/g -e s/draft-mosko-icnrg-ccnxchunking-latest/draft-mosko-icnrg-ccnxchunking-00/g -e s/draft-mosko-icnrg-ccnxserialversion-latest/draft-mosko-icnrg-ccnxserialversion-00/g -e s/draft-mosko-icnrg-ccnxtimeversion-latest/draft-mosko-icnrg-ccnxtimeversion-00/g -e s/draft-mosko-icnrg-ccnxurischeme-latest/draft-mosko-icnrg-ccnxurischeme-00/g -e s/draft-mosko-icnrg-selectors-latest/draft-mosko-icnrg-selectors-00/g -e s/draft-tschudin-icnrg-flic-latest/draft-tschudin-icnrg-flic-00/g $< >$@
